In [66]:
import numpy as np
a = [1,2,3]
b = [4,5,6]
x = 30

In [71]:
print("sum = " , np.sum(a))
print("average = ", np.mean(a))
print("multiply = ", np.multiply(a,b))
print("subtract = ", np.subtract(b,a))
print("Modulus = ", np.mod(b,a))
print("standard deviation = ", np.std(a))
print("variance = ", np.var(a))
print("minimum in array = ", np.min(a))
print("maximum in array = ",np.max(a))
print("ascending order sorting = ", np.sort(a))
print("descending order sorting = ",np.sort(a)[::-1])
print("percentile = ", np.percentile(a,30))
print("median = ", np.median(a))
print("sinx = ", np.sin(x))
print("cosx = ",np.cos(x))
print("tanx =", np.tan(x))
print("sqrtx = ", np.sqrt(x))
print("logarithm", np.log(x))
print("scalar product", np.dot(a,b))
print("roots of a given polynomial cofficients = ", np.roots(a))
print("count the number of element in array = ",np.count_nonzero(a))
print("for checking the deminsion of array = ",np.ndim(a))
print("type checking of array = ", np.ndarray(a))
print("range array =", np.arange(2,100,5))
print("Add evenly spaced values btw interval to array of length = ", np.linspace(2,9,5))
print("Create and array filled with zeros = ",np.zeros((3,3)))
print("Creates an array filled with ones = ", np.ones((3,3)))
print("Creates random array = ", np.random.random((3,3)))
print("Creates an empty array = ", np.empty((3,3)))
print("Creates copy of array = ",np.copy(a))
print("Append items to array = ", np.append(a,b))
print("isert items into array at axis 0 or 1 = ", np.insert(a, 1, 2, 0))
print("Resize array to shape = ", np.resize(a, (2,4)))
print("Deletes items from array = ", np.delete(a,1,0))
print("Concatenates 2 arrays, adds to end = ", np.concatenate((a,b), 0))
print("Stack array row-wise = ", np.vstack((a,b)))
print("Split an array in sub-arrays of (nearly) identical size = ", np.array_split(a, 3))
print("for fixing random state", np.random.seed(7))
print("creat random array in specific numbers", np.random.randint(4, size= (1,2,3,4)))
print("Finding cumsum", np.cumsum(a,0))
print("shape of array = ",np.shape(a))
print("size of array = ",np.size(a,0))
print("the absolute value element-wise = ", np.absolute(a))
print("Return the gradient of an N-dimensional array",np.gradient(a))
print("Return the product of array elements over a given axis :", np.prod(a))
print("Convert angles from degrees to radians: ", np.radians(x))
print("Rounded values :",np.round_([1.23,1.34,1.32], 1))
print("finding unique value:", np.unique([1,1,1,4,2,5,5,7,0,10]))
print("index where label occurs in array: ", np.argmax(a))
print("Generate a uniform random sample: ", np.random.choice(5,3))

sum =  6
average =  2.0
multiply =  [ 4 10 18]
subtract =  [3 3 3]
Modulus =  [0 1 0]
standard deviation =  0.816496580927726
variance =  0.6666666666666666
minimum in array =  1
maximum in array =  3
ascending order sorting =  [1 2 3]
descending order sorting =  [3 2 1]
percentile =  1.6
median =  2.0
sinx =  -0.9880316240928618
cosx =  0.15425144988758405
tanx = -6.405331196646276
sqrtx =  5.477225575051661
logarithm 3.4011973816621555
scalar product 32
roots of a given polynomial cofficients =  [-1.+1.41421356j -1.-1.41421356j]
count the number of element in array =  3
for checking the deminsion of array =  1
type checking of array =  [[[0. 0. 0.]
  [0. 0. 0.]]]
range array = [ 2  7 12 17 22 27 32 37 42 47 52 57 62 67 72 77 82 87 92 97]
Add evenly spaced values btw interval to array of length =  [2.   3.75 5.5  7.25 9.  ]
Create and array filled with zeros =  [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Creates an array filled with ones =  [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Creates random